# Generated by Django 2.2.7 on 2020-01-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktype',
            old_name='type',
            new_name='btype',
        ),
    ]
